spring:
  config:
    activate:
      on-profile: "qa"
build:
  version: "2.0"
accounts:
  message: "Welcome to account QA microservice"
  contactDetails:
    name: "RG"
    email: "rohitgunjal547@gmail.com"
    phone: "8600668541"
