management:
  endpoint:
    web:
      exposure:
        include: "*"
accounts:
  message: "Welcome to the Microservices"
  contactDetails: 
     name: "Rohit Gunjal"
     email: "rohitgunjal547@gmail.com"
