management:
  endpoints:
    web:
      exposure:
        include: "*"
  health: 
    readiness-state:
      enable: true
    liveness-state:
      enable: true
  endpoint:
    health:
      probes:
        enable: true
    refresh:
      enabled: true

accounts:
  message: "Welcome to the Microservices"
  contactDetails: 
     name: "Rohit Gunjal - The Developer"
     email: "rohitgunjal547@gmail.com"
