management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    probes:
      enabled: true
    refresh:
      enabled: true
  endpoint:
    health:
      readiness-state:
        enabled: true
      liveness-state:
        enabled: true
accounts:
  message: "Welcome to the Microservices"
  contactDetails: 
     name: "Rohit Gunjal - The Developer"
     email: "rohitgunjal547@gmail.com"
