management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    refresh:
      enabled: true

accounts:
  message: "Welcome to the Microservices"
  contactDetails: 
     name: "Rohit Gunjal - Developer"
     email: "rohitgunjal547@gmail.com"
