spring:
  config:
    activate:
      on-profile: "prod"
build:
  version: "2.0"
loans:
  message: "Welcome to Loans production microservice"
  contactDetails:
    name: "RG"
    email: "rohitgunjal547@gmail.com"
    phone: "8600668541"
